#!/bin/bash

set -e
set -v

export ID=767689EA4221E44E

(
set -e
set -v
 
# Packages & Packages.gz
dpkg-scanpackages --multiversion . > Packages
gzip -k -f Packages

# Release, Release.gpg & InRelease
apt-ftparchive release . > Release
gpg --default-key "${ID}" -abs -o - Release > Release.gpg
gpg --default-key "${ID}" --clearsign -o - Release > InRelease

# Commit & push
git add -A
git commit -m update
git push
)
